from pathlib import Path

GRID_COLUMNS = 10
GRID_ROWS = 20
BLOCK_SIZE = 30
PLAY_WIDTH = GRID_COLUMNS * BLOCK_SIZE
PLAY_HEIGHT = GRID_ROWS * BLOCK_SIZE
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 700
TOP_LEFT_X = (SCREEN_WIDTH - PLAY_WIDTH) // 2
TOP_LEFT_Y = SCREEN_HEIGHT - PLAY_HEIGHT
SCORES_FILE = Path(__file__).resolve().parents[1] / "scores.txt"
